### ISSUE TITLE
Occasional issue with exceeding boundaries of some sort of list

### ISSUE THREAD

**Issue by LeonardMH** [LeonardMH/namealizer#4]
I received the following error when just using the tool:

```
Traceback (most recent call last):
  File "namealizer", line 212, in <module>
    main()
  File "namealizer", line 204, in main
    string_to_print = "{} {}".format(get_random_word(dictionary), get_random_word(dictionary))
  File "namealizer", line 113, in get_random_word
    word_index = random.randint(0, len(dictionary[starting_letter]) - 1)
IndexError: list index out of range
```

**Comment by LeonardMH** [comment]
I have changed how the dictionaries are implemented internally and I don't think this should be an issue anymore. Furthermore I have written enough unit tests that the test code is more in depth than the module code so I think its safe to call this fixed.
